archetype_icon_paths = {
    "Ancient Gear": "ancient_gear_dark_golem_19847.png",
    "Barrier Statue": "fossil_dyna_pachycephalo_7405.png",
    "Branded": "branded_fusion_17066.png",
    "Bystial": "the_bystial_lubellion_17765.png",
    "Centur-Ion": "centur_ion_primera_19372.png",
    "Chimera": "chimera_fusion_18839.png",
    "Dinomorphia": "dinomorphia_rexterm_17149.png",
    "Dinosaur": "ultimate_conductor_tyranno_13010.png",
    "Dragon Link": "borrelend_dragon_14963.png",
    "Eldlich": "eldlich_the_golden_lord_15123_alt3423_tcg.png",
    "Endymion": "endymion__the_mighty_master_of_magic_14439.png",
    "Evil Eye": "serziel__watcher_of_the_evil_eye_14417.png",
    "Exosister": "exosister_martha_17427.png",
    "Fire King": "legendary_fire_king_ponix_19404.png",
    "Floowandereeze": "floowandereeze___empen_16503.png",
    "Gimmick Puppet": "gimmick_puppet_fantasix_machinix_20221.png",
    "Gold Pride": "gold_pride___star_leon_18458.png",
    "HERO": "elemental_hero_stratos_6784.png",
    "Ice Barrier": "lancea__ancestral_dragon_of_the_ice_mountain_19619.png",
    "Infernoble Knight": "emperor_charles_the_great_18835.png",
    "Kashtira": "kashtira_arise_heart_18191.png",
    "Labrynth": "big_welcome_labrynth_18222.png",
    "Mannadium": "mannadium_riumheart_18475.png",
    "Marincess": "marincess_blue_tang_14631.png",
    "Mathmech": "mathmech_circular_17430.png",
    "Melodious": "bacha_the_melodious_maestra_19876.png",
    "Mikanko": "hu_li_the_jewel_mikanko_18482.png",
    "Naturia": "naturia_mole_cricket_17776.png",
    "Nemleria": "dreaming_nemleria_18478.png",
    "Ninja": "meizen_the_battle_ninja_17795.png",
    "Orcust": "galatea__the_orcust_automaton_13930.png",
    "P.U.N.K.": "ukiyoe_p_u_n_k__amazing_dragon_16731.png",
    "Pendulum Magician": "supreme_king_gate_magician_19143.png",
    "Phantom Knights": "the_phantom_knights_of_torn_scales_15482.png",
    "Plant": "sunavalon_dryas_15861.png",
    "Purrely": "expurrely_noir_18008.png",
    "Raidraptor": "raidraptor___ultimate_falcon_12325.png",
    "Red Dragon Archfiend": "red_dragon_archfiend_7735.png",
    "Rescue-ACE": "rescue_ace_turbulence_17997.png",
    "Ritual Beast": "spiritual_beast_tamer_lara_19631.png",
    "Runick": "runick_fountain_17381.png",
    "Salamangreat": "salamangreat_gazelle_14240.png",
    "Sky Striker": "sky_striker_ace___raye_13670.png",
    "Snake-Eye": "snake_eyes_flamberge_dragon_19152.png",
    "Speedroid": "speedroid_taketomborg_12052.png",
    "Spright": "spright_blue_17405.png",
    "Superheavy Samurai": "superheavy_samurai_soulpiercer_11529.png",
    "Swordsoul": "swordsoul_of_mo_ye_16489.png",
    "Synchron": "junk_speeder_13868.png",
    "Tearlaments": "tearlaments_kitkallos_17444.png",
    "Tech Genus": "t_g__mighty_striker_19176.png",
    "Tenpai Dragon": "tenpai_dragon_chundra_19859.png",
    "Thunder Dragon": "thunder_dragon_titan_13924.png",
    "Traptrix": "traptrix_sera_14203.png",
    "Unchained": "unchained_twins___aruha_14635.png",
    "Vanquish Soul": "vanquish_soul_razen_18727.png",
    "Voiceless Voice": "lo__the_prayers_of_the_voiceless_voice_19474.png",
    "White Forest": "elzette_of_the_white_forest_20193.png",
    "Yubel": "yubel_7409.png"
}
