archetype_icon_paths = {
    "Ancient Gear": "ancient_gear_dark_golem_19847.jpg",
    "Barrier Statue": "fossil_dyna_pachycephalo_7405.jpg",
    "Branded": "branded_fusion_17066.jpg",
    "Bystial": "the_bystial_lubellion_17765.jpg",
    "Centur-Ion": "centur_ion_primera_19372.jpg",
    "Chimera": "chimera_fusion_18839.jpg",
    "Dinomorphia": "dinomorphia_rexterm_17149.jpg",
    "Dinosaur": "ultimate_conductor_tyranno_13010.jpg",
    "Dragon Link": "borrelend_dragon_14963.jpg",
    "Eldlich": "eldlich_the_golden_lord_15123_alt3423_tcg.jpg",
    "Endymion": "endymion__the_mighty_master_of_magic_14439.jpg",
    "Evil Eye": "serziel__watcher_of_the_evil_eye_14417.jpg",
    "Exosister": "exosister_martha_17427.jpg",
    "Fire King": "legendary_fire_king_ponix_19404.jpg",
    "Floowandereeze": "floowandereeze___empen_16503.jpg",
    "Gimmick Puppet": "gimmick_puppet_fantasix_machinix_20221.jpg",
    "Gold Pride": "gold_pride___star_leon_18458.jpg",
    "HERO": "elemental_hero_stratos_6784.jpg",
    "Ice Barrier": "lancea__ancestral_dragon_of_the_ice_mountain_19619.jpg",
    "Infernoble Knight": "emperor_charles_the_great_18835.jpg",
    "Kashtira": "kashtira_arise_heart_18191.jpg",
    "Labrynth": "big_welcome_labrynth_18222.jpg",
    "Mannadium": "mannadium_riumheart_18475.jpg",
    "Marincess": "marincess_blue_tang_14631.jpg",
    "Mathmech": "mathmech_circular_17430.jpg",
    "Melodious": "bacha_the_melodious_maestra_19876.jpg",
    "Mikanko": "hu_li_the_jewel_mikanko_18482.jpg",
    "Naturia": "naturia_mole_cricket_17776.jpg",
    "Nemleria": "dreaming_nemleria_18478.jpg",
    "Ninja": "meizen_the_battle_ninja_17795.jpg",
    "Orcust": "galatea__the_orcust_automaton_13930.jpg",
    "P.U.N.K.": "ukiyoe_p_u_n_k__amazing_dragon_16731.jpg",
    "Pendulum Magician": "supreme_king_gate_magician_19143.jpg",
    "Phantom Knights": "the_phantom_knights_of_torn_scales_15482.jpg",
    "Plant": "sunavalon_dryas_15861.jpg",
    "Purrely": "expurrely_noir_18008.jpg",
    "Raidraptor": "raidraptor___ultimate_falcon_12325.jpg",
    "Red Dragon Archfiend": "red_dragon_archfiend_7735.jpg",
    "Rescue-ACE": "rescue_ace_turbulence_17997.jpg",
    "Ritual Beast": "spiritual_beast_tamer_lara_19631.jpg",
    "Runick": "runick_fountain_17381.jpg",
    "Salamangreat": "salamangreat_gazelle_14240.jpg",
    "Sky Striker": "sky_striker_ace___raye_13670.jpg",
    "Snake-Eye": "snake_eyes_flamberge_dragon_19152.jpg",
    "Speedroid": "speedroid_taketomborg_12052.jpg",
    "Spright": "spright_blue_17405.jpg",
    "Superheavy Samurai": "superheavy_samurai_soulpiercer_11529.jpg",
    "Swordsoul": "swordsoul_of_mo_ye_16489.jpg",
    "Synchron": "junk_speeder_13868.jpg",
    "Tearlaments": "tearlaments_kitkallos_17444.jpg",
    "Tech Genus": "t_g__mighty_striker_19176.jpg",
    "Tenpai Dragon": "tenpai_dragon_chundra_19859.jpg",
    "Thunder Dragon": "thunder_dragon_titan_13924.jpg",
    "Traptrix": "traptrix_sera_14203.jpg",
    "Unchained": "unchained_twins___aruha_14635.jpg",
    "Vanquish Soul": "vanquish_soul_razen_18727.jpg",
    "Voiceless Voice": "lo__the_prayers_of_the_voiceless_voice_19474.jpg",
    "White Forest": "elzette_of_the_white_forest_20193.jpg",
    "Yubel": "phantom_of_yubel_20037.jpg"
}
