archetype_icon_paths = {
    "ABC": "abc_dragon_buster_12590.png",
    "Adamancipator": "adamancipator_researcher_15098.png",
    "Ancient Gear": "ancient_gear_dark_golem_19847.png",
    "Artmage": "artmage_diactorus_21443.png",
    "Auroradon Combo": "mecha_phantom_beast_auroradon_14940.png",
    "Barrier Statue": "fossil_dyna_pachycephalo_7405.png",
    "Beetroopers": "giant_beetrooper_invincible_atlas_16632.png",
    "Blackwings": "black_whirlwind_8203.png",
    "Blue-Eyes": "blue_eyes_spirit_dragon_12324.png",
    "Branded": "branded_fusion_17066.png",
    "Bystial": "the_bystial_lubellion_17765.png",
    "Centur-Ion": "centur_ion_primera_19372.png",
    "Chimera": "chimera_the_king_of_phantom_beasts_18820.png",
    "Crystal Beast": "crystal_beast_sapphire_pegasus_7078.png",
    "Crystron": "crystron_inclusion_20798.png",
    "Cyber Dragon": "cyber_dragon_6390.png",
    "D/D/D": "d_d_savant_kepler_11442.png",
    "Dark Magician": "dark_magician_4041_alt3863.png",
    "Dinomorphia": "dinomorphia_rexterm_17149.png",
    "Dinosaur": "ultimate_conductor_tyranno_13010.png",
    "Dracotail": "dracotail_faimena_21355_ocg.png",
    "Dragon Link": "borrelend_dragon_14963.png",
    "Dragonmaid": "lady_s_dragonmaid_20944.png",
    "Dragoon": "red_eyes_dark_dragoon_14952.png",
    "Drytron": "drytron_mu_beta_fafnir_16004.png",
    "Eldlich": "eldlich_the_golden_lord_15123_alt3423_tcg.png",
    "Endymion": "endymion__the_mighty_master_of_magic_14439.png",
    "Evil Eye": "serziel__watcher_of_the_evil_eye_14417.png",
    "Exodia": "the_unstoppable_exodia_incarnate_20212.png",
    "Exosister": "exosister_martha_17427.png",
    "Fiendsmith": "fiendsmith_engraver_20196.png",
    "Fire King": "legendary_fire_king_ponix_19404.png",
    "Floowandereeze": "floowandereeze___empen_16503.png",
    "Fur Hire": "rex__freight_fur_hire_17783.png",
    "Galaxy Photon": "galaxy_eyes_photon_dragon_9729.png",
    "Gem-Knights": "gem_knight_nepyrim_20932.png",
    "Ghoti": "ghoti_of_the_deep_beyond_17754.png",
    "Gimmick Puppet": "gimmick_puppet_fantasix_machinix_20221.png",
    "Gishki": "evigishki_neremanas_18177.png",
    "Gold Pride": "gold_pride___captain_carrie_18457.png",
    "Grass Chaos": "chaos_ruler__the_chaotic_magical_dragon_15277.png",
    # "HERO": "elemental_hero_stratos_6784.png",
    "HERO": "masked_hero_dark_law_11313.png",
    "Horus": "qebehsenuef__protection_of_horus_19156.png",
    "Ice Barrier": "lancea__ancestral_dragon_of_the_ice_mountain_19619.png",
    "Infernoble Knight": "emperor_charles_the_great_18835.png",
    "Infernoid": "infernoid_devyaty_11707.png",
    "Invoke": "invoked_mechaba_12849.png",
    "Jurrac": "jurrac_meteor_8577.png",
    "K9": "k9_04_noroi_21791.png",
    "Kashtira": "kashtira_arise_heart_18191.png",
    "Labrynth": "lovely_labrynth_of_the_silver_castle_17360_ocg.png",
    "Live☆Twin": "evil_twin_ki_sikil_15626_alt3437_tcg.png",
    "Lunalight": "lunalight_liger_dancer_21441.png",
    "Lyrilusc": "lyrilusc___recital_starling_12862.png",
    "Machina": "machina_fortress_8692.png",
    "Madolche": "madolche_petingcessoeur_14100.png",
    "Magical Musketeer": "magical_musketeer_max_14209.png",
    "Magnet Warrior": "beta_the_electromagnet_warrior_12574.png",
    "Maliss": "maliss__p__dormouse_20584.png",
    "Mannadium": "mannadium_riumheart_18475.png",
    "Marincess": "marincess_blue_tang_14631.png",
    "Mathmech": "mathmech_circular_17430.png",
    "Mecha Phantom Beast": "mecha_phantom_beast_auroradon_14940.png",
    "Megalith": "megalith_aratron_14849.png",
    "Melodious": "bacha_the_melodious_maestra_19876.png",
    "Memento": "mementoal_tecuhtlica___combined_creation_19360.png",
    "Mermail Atlantean": "neptabyss__the_atlantean_prince_11762.png",
    "Mikanko": "hu_li_the_jewel_mikanko_18482.png",
    "Mimighoul": "mimighoul_dragon_20429.png",
    "Mitsurugi": "ame_no_habakiri_no_mitsurugi_21349.png",
    "Monarch": "ehther_the_heavenly_monarch_12090.png",
    "Naturia": "naturia_mole_cricket_17776.png",
    "Nemleria": "dreaming_nemleria_18478.png",
    "Ninja": "meizen_the_battle_ninja_17795.png",
    "Numeron": "numeron_wall_15378.png",
    "Odion": "the_man_with_the_mark_21035.png",
    "Ogdoadic": "nauya__the_ogdoadic_remnant_16072.png",
    "Onomat": "dodododo_warrior_21415.png",
    "Orcust": "galatea__the_orcust_automaton_13930.png",
    "P.U.N.K.": "ukiyoe_p_u_n_k__amazing_dragon_16731.png",
    "Paleozoic": "paleozoic_marrella_12194.png",
    "Pendulum": "supreme_king_gate_magician_19143.png",
    "Pendulum Magician": "supreme_king_gate_magician_19143.png",
    "Phantasm Spiral": "pacifis__the_phantasm_city_12970.png",
    "Phantom Knights": "the_phantom_knights_of_torn_scales_15482.png",
    # "Plant": "lonefire_blossom_7568.png",
    "Plant": "sunvine_sowing_16551.png",
    "Prank-Kids": "prank_kids_battle_butler_14025.png",
    "Predaplant": "predaplant_ambulomelides_17148.png",
    "Purrely": "expurrely_noir_18008.png",
    "Radiant Typhoon": "mystical_space_typhoon_4909.png",
    "Raidraptor": "raidraptor___ultimate_falcon_12325.png",
    "Rank 8 go 2nd": "number_97__draglubion_14566.png",
    "Red Dragon Archfiend": "red_dragon_archfiend_7735.png",
    "Rescue-ACE": "rescue_ace_turbulence_17997.png",
    "Ritual Beast": "spiritual_beast_tamer_lara_19631.png",
    "Regenesis": "regenesis_archfiend_21153.png",
    "Runick": "runick_fountain_17381.png",
    "Ryu-Ge": "sosei_ryu_ge_mistva_20595.png",
    "Ryzeal": "ryzeal_detonator_20578.png",
    "Salamangreat": "salamangreat_gazelle_14240.png",
    "Scareclaw": "scareclaw_tri_heart_17160.png",
    "Shark": "abyss_shark_17039.png",
    "Six Samurai": "gateway_of_the_six_8602.png",
    "Sky Striker": "sky_striker_ace___raye_13670.png",
    "Snake-Eye": "snake_eyes_flamberge_dragon_19152.png",
    "Speedroid": "speedroid_taketomborg_12052.png",
    "SPYRAL": "spyral_double_helix_13371.png",
    "Spright": "spright_blue_17405.png",
    "Subterror": "subterror_guru_13459.png",
    "Superheavy Samurai": "superheavy_samurai_soulpiercer_11529.png",
    "Swordsoul": "swordsoul_of_mo_ye_16489.png",
    "Synchron": "junk_speeder_13868.png",
    "Tachyon": "tachyon_transmigration_11116.png",
    "Tearlaments": "tearlaments_kitkallos_17444.png",
    "Tech Genus": "t_g__mighty_striker_19176.png",
    "Tenpai Dragon": "tenpai_dragon_chundra_19859.png",
    "Thunder Dragon": "thunder_dragon_titan_13924.png",
    "Traptrix": "traptrix_sera_14203.png",
    "Tri-Brigade": "tri_brigade_shuraig_the_ominous_omen_15527.png",
    "True Draco": "master_peace__the_true_dracoslaying_king_12938.png",
    "Umi": "ocean_dragon_lord___kairyu_shin_17047.png",
    "Unchained": "unchained_twins___aruha_14635.png",
    "Utopia": "number_99__utopia_dragonar_16471.png",
    "Vaalmonica": "selettrice_vaalmonica_19863.png",
    "Vanquish Soul": "vanquish_soul_razen_18727.png",
    "Vaylantz": "shinonome_the_vaylantz_priestess_17347.png",
    "Virtual World": "virtual_world_mai_hime___lulu_15489.png",
    "Voiceless Voice": "lo__the_prayers_of_the_voiceless_voice_19474.png",
    "White Forest": "elzette_of_the_white_forest_20193.png",
    "Yubel": "yubel_7409.png",
    "Yummy": "cupsy_yummy_21365_tcg.png",
    "Zoodiac": "zoodiac_drident_12788.png",
}
